# Generated by Django 5.2.5 on 2025-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('hash', models.CharField(max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('role_id', models.IntegerField()),
            ],
        ),
    ]
