"""
Django settings for person_service project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from pathlib import Path

from .middleware.logging import pick_log_dir

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------
import os
from dotenv import load_dotenv

load_dotenv()
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
MODE = os.environ['MODE']
ALLOWED_HOSTS = os.environ['DJANGO_ALLOWED_HOSTS'].split(',')
DB_NAME = os.environ['DB_NAME']
DB_USER = os.environ['DB_USER']
DB_PASSWORD = os.environ['DB_PASSWORD']
DB_DOCKER_HOST = os.environ['DB_DOCKER_HOST']
DB_LOCAL_HOST = os.environ['DB_LOCAL_HOST']
DB_PORT = os.environ['DB_PORT']
ENV_DIR = os.getenv("LOG_DIR", "./logs")
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")

# Определяем папку для логов в зависимости от того где запускаем систему
LOG_DIR = pick_log_dir(BASE_DIR, ENV_DIR)

# Если запускаем локально, то соответствующий хост
if MODE == 'local':
    DB_HOST = DB_LOCAL_HOST
    DEBUG = True
else:
    DB_HOST = DB_DOCKER_HOST
    DEBUG = False

# Куда собирать статику командой collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

ASGI_APPLICATION = "person_service.asgi.application"  # опционально

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,

    }
}


if "test" in sys.argv:  # manage.py test
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
        "TEST": {"NAME": ":memory:"},
    }

os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s "
                      "%(process)d %(threadName)s - %(message)s"
        },
    },
    "handlers": {
        "rotating_file": {
            "level": DJANGO_LOG_LEVEL,
            "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "app.log"),
            "maxBytes": 20 * 1024 * 1024,  # 20 MB
            "backupCount": 10,
            "encoding": "utf-8",
            "delay": True,
        },
    },
    "root": {"handlers": ["rotating_file"], "level": DJANGO_LOG_LEVEL},
    "loggers": {
        "django": {"handlers": ["rotating_file"], "level": DJANGO_LOG_LEVEL, "propagate": False},
        "django.server": {"handlers": ["rotating_file"], "level": DJANGO_LOG_LEVEL, "propagate": False},
        "gunicorn.error": {"handlers": ["rotating_file"], "level": DJANGO_LOG_LEVEL, "propagate": False},
        "gunicorn.access": {"handlers": ["rotating_file"], "level": DJANGO_LOG_LEVEL, "propagate": False},
    },
}
# --------------------------------------------------------------------------


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # для api
    'rest_framework',
    # регистрация приложений
    "person_service.persons.apps.PersonsConfig",
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'person_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'person_service.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
